import { Shell, Button, ImageBox } from "./_shared/Shell";

export function Home(){
  return <Shell><main>
    <section className="prime-hero" style={{backgroundImage:"url(/__mockup/images/prime-hero.jpg)"}}><div className="prime-container"><div className="prime-hero-copy prime-reveal"><div className="prime-eyebrow">PRIME HOSTESS · BRANDIT SOLUTION</div><h1 className="prime-display">Правилните хора за всяко събитие</h1><p className="lead">Подбираме и подготвяме професионалисти, които превръщат присъствието на вашия бранд в преживяване.</p><div className="prime-hero-meta"><Button href="/preview/prime-hostess/Contact" label="Направете запитване"/><span className="prime-kicker">EVERY EVENT. THE RIGHT PEOPLE.</span></div></div></div></section>
    <section className="prime-section"><div className="prime-container"><div className="prime-section-head"><div><div className="prime-eyebrow">С какво помагаме</div><h2 className="prime-display">Събитието започва<br/>преди първия гост.</h2></div><p className="prime-section-intro">От първото посрещане до последния детайл зад кулисите — екипът ни знае как да бъде видим, когато е важно, и невидим, когато трябва.</p></div><div className="prime-service-list">{[["01","Хостеси","Посрещане, регистрация и внимание към всеки гост."],["02","Хостове","Уверено представяне и естествена комуникация."],["03","Промоутъри","Енергия и ясна връзка между хората и продукта."],["04","Brand Ambassadors","Лица, които говорят езика на вашия бранд."],["05","Exhibition Staff","Професионално присъствие на изложения и конгреси."],["06","Automotive Staff","Екипи за премиери, тест драйв и автомобилни активации."]].map(([n,t,p])=><div className="prime-service-item" key={n}><span className="prime-index">{n}</span><div><b>{t}</b><p>{p}</p></div><span className="prime-arrow">↗</span></div>)}</div></div></section>
    <section className="prime-section quiet"><div className="prime-container prime-split"><ImageBox src="/__mockup/images/prime-registration.jpg"/><div className="prime-copy"><div className="prime-eyebrow">Нашият стандарт</div><h2 className="prime-display">Професионализмът се усеща.</h2><div className="prime-rule"/><p>Красивото присъствие е само началото. Нашите хора разбират контекста на събитието, следват брифа и остават спокойни, когато темпото се ускори. Вниманието към гостите не е заучен жест — то е отношение.</p><div className="prime-statline"><div className="prime-stat"><strong>10+</strong><span>години опит</span></div><div className="prime-stat"><strong>500+</strong><span>демо проекта</span></div><div className="prime-stat"><strong>1</strong><span>точен екип</span></div></div><p className="prime-demo-note">Демонстрационни данни за прототипа</p></div></div></section>
    <div className="prime-marquee"><div className="prime-container"><span>WELCOME WITH PURPOSE</span><em>✦</em><span>REPRESENT WITH CONFIDENCE</span><em>✦</em><span>MAKE IT MEMORABLE</span></div></div>
    <section className="prime-section dark"><div className="prime-container prime-split reverse"><div className="prime-copy dark-copy"><div className="prime-eyebrow">Brandit Solution</div><h2 className="prime-display">Опитът зад PRIME.</h2><p>PRIME Hostess е част от Brandit Solution — екип с повече от 10 години опит в промоции, събития и комуникация между брандове и хора. Тази опитност ни помага да мислим не само за визията, а за целия ход на събитието.</p><Button href="/preview/prime-hostess/About" label="Научете повече" ghost/></div><ImageBox src="/__mockup/images/prime-bmw.jpg"/></div></section>
    <section className="prime-section quiet"><div className="prime-container" style={{display:"flex",justifyContent:"space-between",gap:30,alignItems:"end"}}><div><div className="prime-eyebrow">Следващата стъпка</div><h2 className="prime-display" style={{maxWidth:600}}>Разкажете ни за вашето събитие.</h2></div><Button href="/preview/prime-hostess/Contact" label="Започнете разговор"/></div></section>
  </main></Shell>
}
export default Home;