// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prime-hostess/About.tsx": () => import("../components/mockups/prime-hostess/About.tsx"),
  "./components/mockups/prime-hostess/Alexandra.tsx": () => import("../components/mockups/prime-hostess/Alexandra.tsx"),
  "./components/mockups/prime-hostess/BMWEvent.tsx": () => import("../components/mockups/prime-hostess/BMWEvent.tsx"),
  "./components/mockups/prime-hostess/Contact.tsx": () => import("../components/mockups/prime-hostess/Contact.tsx"),
  "./components/mockups/prime-hostess/FAQ.tsx": () => import("../components/mockups/prime-hostess/FAQ.tsx"),
  "./components/mockups/prime-hostess/Home.tsx": () => import("../components/mockups/prime-hostess/Home.tsx"),
  "./components/mockups/prime-hostess/JoinTeam.tsx": () => import("../components/mockups/prime-hostess/JoinTeam.tsx"),
  "./components/mockups/prime-hostess/Portfolio.tsx": () => import("../components/mockups/prime-hostess/Portfolio.tsx"),
  "./components/mockups/prime-hostess/Profiles.tsx": () => import("../components/mockups/prime-hostess/Profiles.tsx"),
  "./components/mockups/prime-hostess/Services.tsx": () => import("../components/mockups/prime-hostess/Services.tsx")
};
